version: "3.7"

services:
    # image project
    app:
        environment:
            - uid=123
            - user=rangel
        container_name: especializati-laravel
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # nginx
    nginx:
        container_name: especializati-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql

networks:
    laravel:
        driver: bridge
